dist: xenial
os: linux
language: node_js
node_js:
    - "14"
branches:
    except:
        - legacy
        - experimental
cache:
    directories:
        - node_modules
before_install:
    - npm update
install:
    - npm install
script:
    - npm run test
