dist: xenial
os: linux
language: node_js
node_js:
    - "14"
branches:
    except:
        - legacy
        - experimental
        - mongoRefactor
cache:
    directories:
        - node_modules
before_install:
    - npm update
install:
    - npm install
    - npm run build
script:
    - npm run test
